export const projects = [
    {
        id: 1,
        grid: "one",
        title: "Nivelo",
        type: "Full-stack",
        description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur modi ipsum asperiores tempora esse ex quas, quam eius explicabo sit?",
        cover: "/projects/nivelo.jpeg",
        tech: [
            "React",
            "NextJS",
            "NodeJS",
            "Express",
            "Apollo",
            "Graphql",
            "PostgreSQL",
            "URQL",
        ],
        repo: "https://github.com/NicolasMarqui/Nivelo",
        live: "https://nivelo.vercel.app/",
    },
    {
        id: 2,
        grid: "two",
        title: "Marca Ponto",
        type: "Front-end",
        description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur modi ipsum asperiores tempora esse ex quas, quam eius explicabo sit?",
        cover: "/projects/nivelo.jpeg",
        tech: [
            "React",
            "NextJS",
            "NodeJS",
            "Express",
            "Apollo",
            "Graphql",
            "PostgreSQL",
            "URQL",
        ],
        repo: "https://github.com/NicolasMarqui/Nivelo",
        live: "https://nivelo.vercel.app/",
    },
    {
        id: 3,
        grid: "three",
        title: "Podcastr",
        type: "Full-stack",
        description:
            "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Aspernatur modi ipsum asperiores tempora esse ex quas, quam eius explicabo sit?",
        cover: "/projects/nivelo.jpeg",
        tech: [
            "React",
            "NextJS",
            "NodeJS",
            "Express",
            "Apollo",
            "Graphql",
            "PostgreSQL",
            "URQL",
        ],
        repo: "https://github.com/NicolasMarqui/Nivelo",
        live: "https://nivelo.vercel.app/",
    },
];
